version: '3.9'

name: otus-homework-env

networks:
  main-network:
    driver: bridge

services:
  otushomework:
    container_name: otushomework
    image: gkoptsev/otushomework:latest
    build:
      context: .
      dockerfile: otushomework/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - main-network
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    container_name: otushomework_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7g0WfNsQziV5r5P
      POSTGRES_DB: otushomework
    ports:
      - "5432:5432"
    networks: 
      - main-network
    volumes:
      - postgres-data:/var/lib/postgressql/data
    restart: always
 
volumes:
  postgres-data:
  
  
